import Link from 'next/link';
export const metadata = { title: 'Données personnelles' };

export default function Page() {
  return <>
    <h1>Données personnelles</h1>
    <section><h2>Responsable et contact</h2><p>Lévy MARQUES est responsable du traitement des données de BOTTT. Pour toute question ou pour exercer tes droits, écris à <a href="mailto:bonjour@bottt.fr">bonjour@bottt.fr</a>, de préférence depuis l’adresse liée à ton compte.</p></section>
    <section><h2>Ce que nous utilisons</h2><p>Le site utilise ton adresse e-mail pour la connexion par code et les messages liés aux soirées. Le profil contient ton prénom ou pseudo, la couleur de ton avatar, ta présentation facultative, ton statut de membre et tes préférences de débutant ou de volontaire MJ.</p><p>Les inscriptions enregistrent la partie, leur statut, le jeton choisi et les dates nécessaires à leur gestion. Les invitations enregistrent le parrain, leur validité et leur utilisation. Les notifications conservent leur contenu et leur état d’envoi. Les informations techniques de connexion servent à sécuriser ton accès et à limiter les abus.</p></section>
    <section><h2>Pourquoi et sur quelle base</h2><p>La gestion du compte, des inscriptions, du parrainage et des messages de service est nécessaire à la fourniture du service que tu demandes, dans le cadre des <Link href="/conditions">conditions d’utilisation</Link>. La sécurité, la prévention des abus et le contrôle des accès reposent sur l’intérêt légitime à protéger le service et ses utilisateurs.</p><p>Les champs facultatifs du profil servent à faire connaissance et peuvent être modifiés ou effacés depuis ton profil. Nous n’utilisons pas tes données pour la publicité ou la prospection commerciale.</p></section>
    <section><h2>Qui peut voir quoi</h2><p>Ton adresse e-mail n’est pas affichée aux autres joueurs. Selon l’accès à la partie, les membres et les participants confirmés peuvent voir les pseudos, les avatars et les volontaires MJ. Les organisateurs accèdent aux informations nécessaires à la gestion des membres et des inscriptions.</p><p>L’adresse précise et le lien de carte privé sont accessibles aux organisateurs et aux participants confirmés. Les visiteurs et les personnes en attente voient uniquement le lieu général.</p><p>Les prestataires techniques d’hébergement, de base de données, d’authentification et d’envoi d’e-mails traitent les informations nécessaires au fonctionnement du service. Le service utilise Supabase pour les comptes et la base ; le déploiement peut utiliser Vercel et Resend. Lorsqu’elle est activée, la vérification anti-abus utilise Cloudflare Turnstile. Pour connaître les prestataires actifs, leurs régions d’hébergement et les garanties applicables à un éventuel transfert hors de l’Union européenne, contacte le responsable.</p></section>
    <section><h2>Conservation</h2><p>La connexion sur un appareil est limitée à 30 jours. Les liens d’invitation sont valables 7 jours. La validation de la politique de cookies est mémorisée sur ton appareil pendant 6 mois.</p><p>Les données de compte, de participation et les messages de service sont conservés tant qu’ils sont nécessaires à la gestion de ton compte, au suivi des soirées et au traitement des demandes ou incidents. La fin de validité d’une connexion ou d’une invitation ne supprime pas automatiquement ces données. Tu peux demander la suppression de ton compte et des données associées au contact indiqué ci-dessus ; certaines informations peuvent être conservées lorsqu’une obligation légale ou le traitement d’un litige le nécessite.</p></section>
    <section><h2>Tes droits</h2><p>Tu peux demander l’accès, la rectification, l’effacement, la limitation ou la portabilité de tes données, dans les conditions prévues par le RGPD, et t’opposer aux traitements fondés sur l’intérêt légitime. Une vérification d’identité peut être nécessaire pour protéger ton compte.</p><p>Tu peux également adresser une réclamation à la <a href="https://www.cnil.fr/fr/adresser-une-plainte" target="_blank" rel="noopener noreferrer">CNIL</a>.</p></section>
    <section><h2>Cartes, agendas et cookies</h2><p>Les services de cartes et d’agenda s’ouvrent uniquement lorsque tu cliques sur leur lien. Si tu choisis Google Agenda ou Outlook, le titre, les horaires, le script et le lieu de la partie sont transmis au service choisi. Un fichier .ics se télécharge directement depuis BOTTT pour être importé dans ton agenda.</p><p>Consulte la <Link href="/cookies">politique de cookies</Link> pour les informations enregistrées sur ton appareil.</p></section>
  </>;
}
