'use client';
import { DateTile } from './date-tile';
import {useState} from 'react';import Link from 'next/link';
import dynamic from 'next/dynamic';
import {Plus,CalendarDays,UsersRound,Clock3,Check,X,Pencil,ShieldCheck,BookOpen} from 'lucide-react';
import type {AppData,GameSession,Booking,Profile} from '@/lib/types';
import {time,statusLabels,sessionUrl} from '@/lib/utils';
import {cancelSession,reviewBooking,setMembership} from '@/app/actions';
import {Dialog} from './dialog';import {Avatar} from './ui';import {Feedback,useAction} from './action-feedback';
const SessionForm = dynamic(() => import('./session-form').then(mod => mod.SessionForm), { loading: () => <p className="muted">Chargement du formulaire…</p> });
export function Admin({data,bookings,profiles,addresses,initialCreate=false}:{data:AppData;bookings:Booking[];profiles:Profile[];addresses:Record<string,string>;initialCreate?:boolean}){
 const [tab,setTab]=useState<'sessions'|'requests'|'members'>('sessions');const [editing,setEditing]=useState<GameSession|'new'|null>(initialCreate?'new':null);const [selected,setSelected]=useState<GameSession|null>(null);const [cancel,setCancel]=useState<GameSession|null>(null);const [member,setMember]=useState<Profile|null>(null);const [removing,setRemoving]=useState<Booking|null>(null);const a=useAction();
 const future=data.sessions.filter(s=>s.status==='published'&&new Date(s.ends_at)>new Date());const pending=bookings.filter(b=>b.status==='pending'&&future.some(s=>s.id===b.session_id));
 const template=[...data.sessions].filter(s=>s.status==='published').sort((a,b)=>Date.parse(b.starts_at)-Date.parse(a.starts_at))[0];
 const review=(b:Booking,approve:boolean)=>a.run(()=>reviewBooking(b.id,approve));
 return <><div className="page-heading admin-heading"><h1>Organiser</h1><button className="button primary compact" onClick={()=>setEditing('new')}><Plus size={17}/>Créer une partie</button></div>
 <div className="admin-stats"><div><CalendarDays/><span><strong>{future.length}</strong>sessions à venir</span></div><div><UsersRound/><span><strong>{profiles.filter(p=>p.membership!=='suspended').length}</strong>personnes dans le cercle</span></div><div><Clock3/><span><strong>{pending.length}</strong>demandes à valider</span></div></div>
 <div className="session-tabs admin-tabs" role="group" aria-label="Espace organisateur">{([['sessions','Les sessions'],['requests',`À valider (${pending.length})`],['members','Les membres']] as const).map(([value,label])=><button key={value} aria-pressed={tab===value} className={tab===value?'selected':''} onClick={()=>setTab(value)}>{label}</button>)}</div><Feedback result={a.result}/>
 {tab==='sessions'?<div className="admin-session-list">{data.sessions.length?data.sessions.map(s=><article className="admin-session-row" key={s.id}><DateTile date={s.starts_at} /><div className="admin-session-name"><Link href={sessionUrl(s.id)}><h2>{s.title}</h2></Link><p>{s.script} · {time(s.starts_at)} · {s.status==='cancelled'?'Annulée':s.visibility==='public'?'Ouverte à tous':'Membres et invités'}</p></div><span className="badge">{s.confirmed_count}/{s.capacity} inscrits</span><div className="row-actions"><button className="button secondary compact" onClick={()=>setSelected(s)}><UsersRound size={15}/>Participants</button>{s.status==='published'&&<><button aria-label={`Modifier ${s.title}`} className="icon-btn" onClick={()=>setEditing(s)}><Pencil size={17}/></button><button aria-label={`Annuler ${s.title}`} className="icon-btn" onClick={()=>setCancel(s)}><X size={17}/></button></>}</div></article>):<div className="empty-state"><CalendarDays/><h2>Crée votre première soirée.</h2><p>Tu choisis la date, le script et les places disponibles.</p></div>}</div>:tab==='requests'?<div className="panel">{pending.length?pending.map(b=><div className="request-row" key={b.id}><Avatar name={b.profile?.display_name||'Joueur'} color={b.profile?.avatar_color}/><div><h3>{b.profile?.display_name}</h3><p>{data.sessions.find(s=>s.id===b.session_id)?.title}</p><small>{b.profile?.beginner?'Découvre le jeu':'Connaît déjà le jeu'}</small></div><div className="row-actions"><button className="button quiet compact" disabled={a.pending} onClick={()=>review(b,true)}><Check size={15}/>Accepter</button><button className="icon-btn" disabled={a.pending} aria-label={`Refuser la demande de ${b.profile?.display_name}`} onClick={()=>setRemoving(b)}><X size={17}/></button></div></div>):<div className="empty-state borderless"><ShieldCheck size={35}/><h2>Tout est à jour.</h2><p>Les premières demandes des nouveaux joueurs apparaîtront ici.</p></div>}</div>:<div className="panel">{profiles.map(p=><div className="member-row" key={p.id}><Avatar name={p.display_name} color={p.avatar_color}/><div><h3>{p.display_name}</h3><p>{p.bio|| (p.beginner?'Découvre le jeu':'Connaît déjà le jeu')}</p></div><span className={`badge ${p.membership==='suspended'?'red':''}`}>{({organizer:'Organisation',member:'Membre',newcomer:'Nouveau',suspended:'Suspendu'})[p.membership]}</span>{p.membership!=='organizer'&&<button className="button secondary compact" disabled={a.pending} onClick={()=>setMember(p)}>{p.membership==='suspended'?'Réactiver':'Gérer'}</button>}</div>)}</div>}
 <Dialog title={editing==='new'?'Créer une partie': 'Modifier la partie'} open={editing!==null} onClose={()=>setEditing(null)} wide>{editing&&<SessionForm session={editing==='new'?undefined:editing} template={template} address={editing==='new'?(template?addresses[template.id]:undefined):addresses[editing.id]} onSaved={()=>setEditing(null)}/>}</Dialog>
 <Dialog title={selected?.title||'Participants'} open={!!selected} onClose={()=>setSelected(null)} wide><div className="stack">{selected&&bookings.filter(b=>b.session_id===selected.id&&!['cancelled','declined'].includes(b.status)).map(b=><div className="request-row" key={b.id}><Avatar name={b.profile?.display_name||'Joueur'} color={b.profile?.avatar_color}/><div><h3 className="participant-name">{b.profile?.display_name}{b.profile?.can_storytell&&<BookOpen size={15} role="img" aria-label="Volontaire MJ"><title>Volontaire MJ</title></BookOpen>}</h3><p>{b.pool==='newcomer'?'Quota nouveaux':'Quota cercle'}</p></div><span className="badge">{statusLabels[b.status]}</span>{b.status==='pending'?<button className="button quiet compact" disabled={a.pending} onClick={()=>review(b,true)}>Valider</button>:null}<button className="icon-btn" aria-label={`Retirer ${b.profile?.display_name}`} disabled={a.pending} onClick={()=>setRemoving(b)}><X size={16}/></button></div>)}{selected&&!bookings.some(b=>b.session_id===selected.id&&!['cancelled','declined'].includes(b.status))&&<p className="muted">Pas encore de participation.</p>}<Feedback result={a.result}/></div></Dialog>
 <Dialog title="Retirer cette participation ?" open={!!removing} onClose={()=>setRemoving(null)}><div className="stack"><p>{removing?.profile?.display_name} sera prévenu·e. Une éventuelle place libérée sera proposée à la liste d’attente.</p><button className="button danger" disabled={a.pending} onClick={()=>removing&&a.run(()=>reviewBooking(removing.id,false),()=>setRemoving(null))}>Retirer la participation</button><Feedback result={a.result}/></div></Dialog>
 <Dialog title="Annuler cette soirée ?" open={!!cancel} onClose={()=>setCancel(null)}><div className="stack"><p>La session « {cancel?.title} » sera annulée et les participants seront prévenus.</p><button className="button danger" disabled={a.pending} onClick={()=>cancel&&a.run(()=>cancelSession(cancel.id),()=>setCancel(null))}>Confirmer l’annulation</button><Feedback result={a.result}/></div></Dialog>
 <Dialog title={`Le compte de ${member?.display_name||''}`} open={!!member} onClose={()=>setMember(null)}><div className="stack"><p>{member?.membership==='suspended'?'Réactiver ce compte lui permettra de participer à nouveau.':'La suspension bloque les inscriptions et libère les places futures de cette personne.'}</p><button className={`button ${member?.membership==='suspended'?'primary':'danger'}`} disabled={a.pending} onClick={()=>member&&a.run(()=>setMembership(member.id,member.membership==='suspended'?'member':'suspended'),()=>setMember(null))}>{member?.membership==='suspended'?'Réactiver le compte':'Suspendre le compte'}</button>{member?.membership==='newcomer'&&<button className="button secondary" disabled={a.pending} onClick={()=>a.run(()=>setMembership(member!.id,'member'),()=>setMember(null))}>Valider comme membre</button>}<Feedback result={a.result}/></div></Dialog>
 </>;
}
