'use client';
import {useState} from 'react';import Link from 'next/link';
import {Plus,CalendarDays,UsersRound,Clock3,Check,X,Pencil,MoreHorizontal,ShieldCheck,Search,BookOpen} from 'lucide-react';
import {MIN_PLAYERS,DEFAULT_CAPACITY,MAX_CAPACITY} from '@/lib/session-rules';
import type {AppData,GameSession,Booking,Profile} from '@/lib/types';
import {dateLong,time,statusLabels,sessionUrl,parisInput,fromParisInput} from '@/lib/utils';
import {saveSession,cancelSession,reviewBooking,setMembership} from '@/app/actions';
import {Dialog} from './dialog';import {Avatar} from './ui';import {Feedback,useAction} from './action-feedback';
function SessionForm({session,address,onSaved}:{session?:GameSession;address?:string;onSaved:()=>void}){const a=useAction();return <form className="stack session-form" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);try{const payload={...(session?{id:session.id}:{}),title:String(f.get('title')),script:String(f.get('script')),starts_at:fromParisInput(String(f.get('starts_at'))),ends_at:fromParisInput(String(f.get('ends_at'))),location:String(f.get('location')),address:String(f.get('address')),capacity:Number(f.get('capacity')),newcomer_seats:Number(f.get('newcomer_seats')),release_hours:Number(f.get('release_hours')),visibility:String(f.get('visibility'))};a.run(()=>saveSession(payload),onSaved);}catch(err){a.setResult({ok:false,message:err instanceof Error?err.message:'Vérifie les dates.'});}}}>
 <label className="field">Nom de la soirée<input name="title" required minLength={3} maxLength={100} defaultValue={session?.title} placeholder="Une nuit à Ravenswood"/></label>
 <label className="field">Script<input name="script" required list="scripts" minLength={2} maxLength={100} defaultValue={session?.script||'Trouble Brewing'}/><datalist id="scripts"><option>Trouble Brewing</option><option>Bad Moon Rising</option><option>Sects &amp; Violets</option></datalist></label>
 <div className="form-grid"><label className="field">Début · heure de Paris<input name="starts_at" required type="datetime-local" defaultValue={session?parisInput(session.starts_at):undefined}/></label><label className="field">Fin · heure de Paris<input name="ends_at" required type="datetime-local" defaultValue={session?parisInput(session.ends_at):undefined}/></label></div>
 <label className="field">Lieu affiché à tous<input name="location" required minLength={2} maxLength={150} defaultValue={session?.location} placeholder="Ville ou quartier"/></label>
 <label className="field">Adresse précise <span className="field-note">Visible uniquement des inscrits confirmés</span><textarea name="address" maxLength={500} rows={2} defaultValue={address} placeholder="Adresse, accès, informations utiles…"/></label>
 <div className="form-grid three"><label className="field">Places joueurs <span className="field-note">7 minimum · 15 par défaut</span><input name="capacity" type="number" required min={MIN_PLAYERS} max={MAX_CAPACITY} defaultValue={session?.capacity??DEFAULT_CAPACITY}/></label><label className="field">Dont nouveaux<input name="newcomer_seats" type="number" required min={0} max={MAX_CAPACITY} defaultValue={session?.newcomer_seats??3}/></label><label className="field">Quotas réunis à<select name="release_hours" defaultValue={session?.release_hours??72}><option value={0}>L’heure de début</option><option value={24}>J−1</option><option value={48}>J−2</option><option value={72}>J−3</option><option value={168}>J−7</option></select></label></div>
 <label className="field">Visibilité<select name="visibility" defaultValue={session?.visibility||'public'}><option value="public">Ouverte à tous</option><option value="members">Membres et personnes parrainées</option></select></label>
 <Feedback result={a.result}/><button className="button primary full" disabled={a.pending}>{a.pending?'Enregistrement…':session?'Enregistrer les modifications':'Publier la session'}</button>
 </form>;}
export function Admin({data,bookings,profiles,addresses,initialCreate=false}:{data:AppData;bookings:Booking[];profiles:Profile[];addresses:Record<string,string>;initialCreate?:boolean}){
 const [tab,setTab]=useState<'sessions'|'requests'|'members'>('sessions');const [editing,setEditing]=useState<GameSession|'new'|null>(initialCreate?'new':null);const [selected,setSelected]=useState<GameSession|null>(null);const [cancel,setCancel]=useState<GameSession|null>(null);const [member,setMember]=useState<Profile|null>(null);const [removing,setRemoving]=useState<Booking|null>(null);const a=useAction();
 const future=data.sessions.filter(s=>s.status==='published'&&new Date(s.ends_at)>new Date());const pending=bookings.filter(b=>b.status==='pending'&&future.some(s=>s.id===b.session_id));
 const review=(b:Booking,approve:boolean)=>a.run(()=>reviewBooking(b.id,approve));
 return <><div className="page-heading admin-heading"><h1>Organiser</h1><button className="button primary compact" onClick={()=>setEditing('new')}><Plus size={17}/>Créer une partie</button></div>
 <div className="admin-stats"><div><CalendarDays/><span><strong>{future.length}</strong>sessions à venir</span></div><div><UsersRound/><span><strong>{profiles.filter(p=>p.membership!=='suspended').length}</strong>personnes dans le cercle</span></div><div><Clock3/><span><strong>{pending.length}</strong>demandes à valider</span></div></div>
 <div className="session-tabs admin-tabs" role="group" aria-label="Espace organisateur">{([['sessions','Les sessions'],['requests',`À valider (${pending.length})`],['members','Les membres']] as const).map(([value,label])=><button key={value} aria-pressed={tab===value} className={tab===value?'selected':''} onClick={()=>setTab(value)}>{label}</button>)}</div><Feedback result={a.result}/>
 {tab==='sessions'?<div className="admin-session-list">{data.sessions.length?data.sessions.map(s=><article className="admin-session-row" key={s.id}><div className="date-tile"><strong>{new Intl.DateTimeFormat('fr',{day:'2-digit',timeZone:'Europe/Paris'}).format(new Date(s.starts_at))}</strong><span>{new Intl.DateTimeFormat('fr',{month:'short',timeZone:'Europe/Paris'}).format(new Date(s.starts_at))}</span></div><div className="admin-session-name"><Link href={sessionUrl(s.id)}><h2>{s.title}</h2></Link><p>{s.script} · {time(s.starts_at)} · {s.status==='cancelled'?'Annulée':s.visibility==='public'?'Ouverte à tous':'Membres et invités'}</p></div><span className="badge">{s.confirmed_count}/{s.capacity} inscrits</span><div className="row-actions"><button className="button secondary compact" onClick={()=>setSelected(s)}><UsersRound size={15}/>Participants</button>{s.status==='published'&&<><button aria-label={`Modifier ${s.title}`} className="icon-btn" onClick={()=>setEditing(s)}><Pencil size={17}/></button><button aria-label={`Annuler ${s.title}`} className="icon-btn" onClick={()=>setCancel(s)}><X size={17}/></button></>}</div></article>):<div className="empty-state"><CalendarDays/><h2>Crée votre première soirée.</h2><p>Tu choisis la date, le script et les places disponibles.</p></div>}</div>:tab==='requests'?<div className="panel">{pending.length?pending.map(b=><div className="request-row" key={b.id}><Avatar name={b.profile?.display_name||'Joueur'} color={b.profile?.avatar_color}/><div><h3>{b.profile?.display_name}</h3><p>{data.sessions.find(s=>s.id===b.session_id)?.title}</p><small>{b.profile?.beginner?'Découvre le jeu':'Connaît déjà le jeu'}</small></div><div className="row-actions"><button className="button quiet compact" disabled={a.pending} onClick={()=>review(b,true)}><Check size={15}/>Accepter</button><button className="icon-btn" disabled={a.pending} aria-label={`Refuser la demande de ${b.profile?.display_name}`} onClick={()=>setRemoving(b)}><X size={17}/></button></div></div>):<div className="empty-state borderless"><ShieldCheck size={35}/><h2>Tout est à jour.</h2><p>Les premières demandes des nouveaux joueurs apparaîtront ici.</p></div>}</div>:<div className="panel">{profiles.map(p=><div className="member-row" key={p.id}><Avatar name={p.display_name} color={p.avatar_color}/><div><h3>{p.display_name}</h3><p>{p.bio|| (p.beginner?'Découvre le jeu':'Connaît déjà le jeu')}</p></div><span className={`badge ${p.membership==='suspended'?'red':''}`}>{({organizer:'Organisation',member:'Membre',newcomer:'Nouveau',suspended:'Suspendu'})[p.membership]}</span>{p.membership!=='organizer'&&<button className="button secondary compact" disabled={a.pending} onClick={()=>setMember(p)}>{p.membership==='suspended'?'Réactiver':'Gérer'}</button>}</div>)}</div>}
 <Dialog title={editing==='new'?'Une nouvelle soirée': 'Modifier la session'} open={editing!==null} onClose={()=>setEditing(null)} wide>{editing&&<SessionForm session={editing==='new'?undefined:editing} address={editing==='new'?undefined:addresses[editing.id]} onSaved={()=>setEditing(null)}/>}</Dialog>
 <Dialog title={selected?.title||'Participants'} open={!!selected} onClose={()=>setSelected(null)} wide><div className="stack">{selected&&bookings.filter(b=>b.session_id===selected.id&&!['cancelled','declined'].includes(b.status)).map(b=><div className="request-row" key={b.id}><Avatar name={b.profile?.display_name||'Joueur'} color={b.profile?.avatar_color}/><div><h3 className="participant-name">{b.profile?.display_name}{b.profile?.can_storytell&&<BookOpen size={15} role="img" aria-label="Volontaire MJ"><title>Volontaire MJ</title></BookOpen>}</h3><p>{b.pool==='newcomer'?'Quota nouveaux':'Quota cercle'}</p></div><span className="badge">{statusLabels[b.status]}</span>{b.status==='pending'?<button className="button quiet compact" disabled={a.pending} onClick={()=>review(b,true)}>Valider</button>:null}<button className="icon-btn" aria-label={`Retirer ${b.profile?.display_name}`} disabled={a.pending} onClick={()=>setRemoving(b)}><X size={16}/></button></div>)}{selected&&!bookings.some(b=>b.session_id===selected.id&&!['cancelled','declined'].includes(b.status))&&<p className="muted">Pas encore de participation.</p>}<Feedback result={a.result}/></div></Dialog>
 <Dialog title="Retirer cette participation ?" open={!!removing} onClose={()=>setRemoving(null)}><div className="stack"><p>{removing?.profile?.display_name} sera prévenu·e. Une éventuelle place libérée sera proposée à la liste d’attente.</p><button className="button danger" disabled={a.pending} onClick={()=>removing&&a.run(()=>reviewBooking(removing.id,false),()=>setRemoving(null))}>Retirer la participation</button><Feedback result={a.result}/></div></Dialog>
 <Dialog title="Annuler cette soirée ?" open={!!cancel} onClose={()=>setCancel(null)}><div className="stack"><p>La session « {cancel?.title} » sera annulée et les participants seront prévenus.</p><button className="button danger" disabled={a.pending} onClick={()=>cancel&&a.run(()=>cancelSession(cancel.id),()=>setCancel(null))}>Confirmer l’annulation</button><Feedback result={a.result}/></div></Dialog>
 <Dialog title={`Le compte de ${member?.display_name||''}`} open={!!member} onClose={()=>setMember(null)}><div className="stack"><p>{member?.membership==='suspended'?'Réactiver ce compte lui permettra de participer à nouveau.':'La suspension bloque les inscriptions et libère les places futures de cette personne.'}</p><button className={`button ${member?.membership==='suspended'?'primary':'danger'}`} disabled={a.pending} onClick={()=>member&&a.run(()=>setMembership(member.id,member.membership==='suspended'?'member':'suspended'),()=>setMember(null))}>{member?.membership==='suspended'?'Réactiver le compte':'Suspendre le compte'}</button>{member?.membership==='newcomer'&&<button className="button secondary" disabled={a.pending} onClick={()=>a.run(()=>setMembership(member!.id,'member'),()=>setMember(null))}>Valider comme membre</button>}<Feedback result={a.result}/></div></Dialog>
 </>;
}
