import type { AppData, GameSession, Profile } from './types';
export const demoProfile: Profile = { id: 'demo-camille', display_name: 'Camille', bio: 'Toujours partante pour une bonne histoire.', avatar_color: 'rose', beginner: false, can_storytell: false, membership: 'organizer', sponsored_by: null };
const people = [ ['Léa', 'rose'], ['Thomas', 'blue'], ['Manon', 'sage'], ['Hugo', 'ochre'], ['Sarah', 'lilac'] ].map(([display_name, avatar_color]) => ({ display_name, avatar_color }));
export function demoSessions(): GameSession[] {
  const start = new Date(); start.setUTCDate(start.getUTCDate() + ((5 - start.getUTCDay() + 7) % 7 || 7)); start.setUTCHours(17, 30, 0, 0);
  const date = (days: number, hours = 0) => new Date(start.getTime() + (days * 24 + hours) * 3600000).toISOString();
  return [
    { id: 'une-nuit-a-ravenswood', title: 'Une nuit à Ravenswood', description: 'Un village tranquille. Quelques secrets. Et probablement un démon parmi nous. On se retrouve autour de Trouble Brewing pour une soirée de bluff et de belles accusations.\n\nAccueil à 19h30, explication des règles puis première partie à 20h. Prévois ta soirée et, si tu veux, quelque chose à grignoter. Les nouveaux sont les bienvenus : on t’explique tout sur place.', script: 'Trouble Brewing', starts_at: date(0), ends_at: date(0, 4), location: 'Paris · lieu à confirmer', capacity: 12, newcomer_seats: 3, release_hours: 72, beginners_welcome: true, visibility: 'public', status: 'published', confirmed_count: 8, waitlist_count: 0, my_status: null, participants: people },
    { id: 'sous-la-lune-rouge', title: 'Sous la lune rouge', description: 'Une soirée Bad Moon Rising pour celles et ceux qui ont déjà quelques parties derrière eux. Attends-toi à des nuits mouvementées et à des théories qui ne tiennent pas longtemps.', script: 'Bad Moon Rising', starts_at: date(7), ends_at: date(7, 4), location: 'Paris · lieu à confirmer', capacity: 12, newcomer_seats: 2, release_hours: 72, beginners_welcome: true, visibility: 'members', status: 'published', confirmed_count: 12, waitlist_count: 2, my_status: null, participants: [...people].reverse() },
    { id: 'bienvenue-au-village', title: 'Bienvenue au village', description: 'Ta toute première partie ? Cette session est pour toi. On prend le temps de découvrir le jeu ensemble, de poser des questions et de rencontrer le cercle. Aucune expérience nécessaire.', script: 'Trouble Brewing', starts_at: date(15, -4), ends_at: date(15, 0), location: 'Paris · lieu à confirmer', capacity: 10, newcomer_seats: 4, release_hours: 72, beginners_welcome: true, visibility: 'public', status: 'published', confirmed_count: 4, waitlist_count: 0, my_status: 'confirmed', participants: people.slice(0, 3) },
    { id: 'les-murmures-du-cercle', title: 'Les murmures du cercle', description: 'Des informations contradictoires, des conversations à voix basse et beaucoup de bonnes raisons de douter. Une soirée Sects & Violets pour les joueurs qui connaissent déjà les bases.', script: 'Sects & Violets', starts_at: date(21), ends_at: date(21, 4), location: 'Paris · lieu à confirmer', capacity: 12, newcomer_seats: 2, release_hours: 72, beginners_welcome: true, visibility: 'public', status: 'published', confirmed_count: 6, waitlist_count: 0, my_status: null, participants: people.slice(1) }
  ];
}
export function initialDemo(): AppData { return { profile: demoProfile, sessions: demoSessions(), invitations: [], notices: [], demo: true, configured: false }; }
